### PR TITLE
fixed tax calculation

### PR DESCRIPTION
**Pull request by sgoodwin10**
fixed tax calculation.

should maybe have option to select included or excluded to product or order.

### CODE REVIEW

**Comment by jHoldroyd** [comment]
Thanks for that, must have missed it during testing.

We're working on multiple-currencies for version 1.2.0 and these tax options are something we'll be considering a lot before then to make it as dynamic yet simple as we can.

**Comment by sgoodwin10** [comment]
no... the subtotal needs to be adjusted to take the tax amount away from the total to get the sub total.

do you want me to do that?

**Comment by jHoldroyd** [comment]
Ok I'm going to blame this on Google, we checked the numbers over and over on their calculator and it said we were right, just went back over the numbers properly and found out yours is correct. It'll be staying in place and I'm now going to go hide under a rock -.-

**Comment by sgoodwin10** [comment]
haha... all good.

This one has caught me out before in a few old CMS's - its been in the back of my mind since.

btw: today was the first day of using firesale... awesome work. Was worried i was going to have to write a cart system for a custom module i wrote that was selling something offbeat. Installed firesale..., add a "add to cart" in my custom module, went to the firesale/cart and crossed my fingers... it worked straight out of the box!!! F**king awesome!!! (just saved me a bunch few days).

Expect some help/ideas/bug reports (if any) over the next few days.

**Comment by jHoldroyd** [comment]
Look forward to it, we're always happy to hear new ideas and suggestions, even issues that correct us on our poor math skills! Glad you're finding it useful though and thanks again for the fix.

**Pull request merged**
