### PR TITLE
Category query problem

### PR DESCRIPTION
**Pull request by nickrichwi**
I'm trying to understand why its happening and what i'm seeing...  
On the backend my four products all have the correct category in the edit and index screen of products.  But on the front end that category shows only 2 of the products in the category??? all products are Live, as is the category.  

Digging around the select statement ( build_query in categories ) seems to be flawed .. ( maybe im wrong ), there isn't a reason to use a second join to pull the category information when your only retrieving product ids.

### CODE REVIEW

**Comment by jHoldroyd** [comment]
There's a definite reason for the grouping by slug and that's simply when we do multiple product options we group them by that field so only one is shown in the results. The other changes you made seem correct but until version 1.2 we'll have to leave the slug as the group by, at which point the new product variant system will be in place and we can leave that behind.

**Comment by nickrichwi** [comment]
Ok, if a product slug is unique in the system the primary key can also be used which is the product id also.. alright cool.

**Comment by jHoldroyd** [comment]
The slug isn't unique, multiple products can have the same slug, but it's just the field we group them on in case they're different versions of the same product. We went with this option because even with different product variations the product code/title is quite likely to be different.

**Comment by jHoldroyd** [comment]
I'll merge this now, but will be rolling back to the group by on the slug as at the moment it is required. We'll address that in the future, as for the join you removed I have a feeling that was a left over from the old way of doing things.

**Pull request merged**
