### PR TITLE
Added French translation.

### PR DESCRIPTION
**Pull request by Dixens**

### CODE REVIEW

**Comment by Dixens** [comment]
That's very nice of you, thanx. I'll keep on watching out the changes.

**Comment by jHoldroyd** [comment]
Least we could do really, I'll let you know when things are ready and we'll hook you up :)

**Comment by Dixens** [comment]
Hi there,

Your French translator again...

Just saw that your doc system is more or less finished now and available at github.com. I'd like to carry on helping out with another batch of French translation but as there is no language files, I am a bit stuck. Maybe you don't need a French translation of these docs for the time being?

**Comment by jHoldroyd** [comment]
The system doesn't allow for translations at the moment, but if you want to clone it and we can figure something out, possibly a seperate install under fr.docs.getfiresale.org ...just a thought. But there's still a lot to write for the docs, while the system is in place, many of the content pages are still to be filled in and I think having to translate them with constant updates will be a little much to expect.

So it may be a better option to wait until more is written or we can figure something out that will work better in the long run for translations.

Thank you very much for the offer though, it is appreciated.

**Comment by Dixens** [comment]
I understand. I'll keep on watching this repo just in case then - do not hesitate to keep me posted about any evolution of course.

**Pull request merged**
