### PR TITLE
PyroStreams-Multiple-Relationships

### PR DESCRIPTION
**Pull request by ChristianGiupponi**
Added the installation step for the PyroCMS Community users

### CODE REVIEW

**Comment by jHoldroyd** [comment]
Thanks for that

**Comment by agrantham** [comment]
Every single time I come across this link:

https://github.com/parse19/PyroStreams-Multiple-Relationships

I get a 404 error. Can someone please direct me to the right page to get the Multiple-Relationships so I can install it and continue with my FireSale install :(

**Comment by chrisnharvey** [comment]
Looks like it has been moved to @adamfairholm's GitHub profile.

Try this link:
https://github.com/adamfairholm/PyroStreams-Multiple-Relationships

Sent from my iPhone

On 22 Feb 2013, at 01:14 AM, agrantham notifications@github.com wrote:

Every single time I come across this link:

https://github.com/parse19/PyroStreams-Multiple-Relationships

I get a 404 error. Can someone please direct me to the right page to get
the Multiple-Relationships so I can install it and continue with my
FireSale install :(

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/pull/33#issuecomment-13923365.

**Comment by egahmad** [comment]
Each time i try to add a new entry with a multi-relation field assigned to a stream i get this error

A PHP Error was encountered

Severity: Notice

Message: Undefined index: row_edit_id

Filename: multiple/field.multiple.php

Line Number: 88

**Comment by adamfairholm** [comment]
@egahmad,

This was a result of a dev switching the class var $alt_process to false when it should be true. If you grab the latest MR (2.0.1), this issue should be gone:

https://github.com/adamfairholm/PyroStreams-Multiple-Relationships

Adam

**Comment by egahmad** [comment]
WOW this is so fast, I dooooo appreciate it, thanks a lot

**Pull request merged**
