### PR TITLE
Polish language files for 1.2/develop

### PR DESCRIPTION
**Pull request by FornetMK**
Polish language files for 1.2

Done some corrections and style improvements, 
Updated details.php (no email templates yet).

### CODE REVIEW

**Comment by ChristianGiupponi** [comment]
@FornetMK this pull request cannot be automatically merged.
Try to send another one.

**Comment by jHoldroyd** [comment]
We've been trying to get it in but every time we try to cherrypick the last 2 commits it causes massive conflicts throughout the system for some reason. I'll give it another try now but it'll probably just need manually copied and committed by us.

**Comment by FornetMK** [comment]
Ill resend the pull again, maybe crashed something.

**Comment by jHoldroyd** [comment]
It's fine, I've just manually merged this in. Closing now and thanks again for the contribution.

**Pull request closed without merging**
