### PR TITLE
Categories plugin ordering

### PR DESCRIPTION
**Pull request by iknowfoobar**
I have updated the categories plugin ordering to match the documentation at 
https://www.getfiresale.org/documentation/themeing/plugins/categories

I have also set it to default to the tree ordering when no ordering is specified as users are confused when the ordering doesn't match the admin area ordering.

### CODE REVIEW

**Comment by jHoldroyd** [comment]
Thanks for this, but wouldn't something like this work:

``` php
if ( ! isset($attributes['order']) and ! isset($attributes['order-by']) ) {
    $attributes['order'] = 'ordering_count asc';
} else if ( isset($attribtes['order-by']) ) {
    $attributes['order'] = $attribtes['order-by'].' '.( isset($attribtes['order-dir']) ? $attribtes['order-dir'] : 'asc' );
}
```

That would remove the need for any extra code as it would use existing methods.

**Comment by iknowfoobar** [comment]
Something like that would work, I actually didn't notice you had the order attribute there as I was looking for order-by hence my extra code.

I'll update my commit :)

**Comment by jHoldroyd** [comment]
Thanks again, still working on figuring out your other issues at the moment

**Comment by iknowfoobar** [comment]
Cheers, yeah the modifier one is something we really need. We have a lot more ideas for features for firesale. We are normally Symfony in house but with no decent CMS in Symfony2 yet (we don't have the resources to build one) we have opted to go for PyroCMS and need a rock solid ecommerce platform to work with.

Might be work a chat sometime.

**Comment by jHoldroyd** [comment]
I've not seen the issues you've been having before, I encountered another issue earlier that seemed similar which was fixed but it doesn't see we got the one you're having. Still digging until we get it though.

Byt yeah if you ever want to chat just mail me (jamie@getfiresale.org).

**Pull request merged**
