### PR TITLE
Changes to Default Currency

### PR DESCRIPTION
**Pull request by jchamberlain**
In settings:
Instead of typing in a currency code, the admin can now select a currency from the list. I left the underlying value unchanged as the cur_code (though I think perhaps the id would make more sense), so this shouldn't have any ramifications elsewhere. I also set that list to be updated whenever a change is made in currencies.

Everywhere else:
Previously, everything defaulted to a hard-coded currency id 1, regardless of the Default Currency Code in the admin. Wherever I could find it, I removed the 1 or changed it to NULL. I then let the currency_m model grab the default currency if none is specified. I removed all the 1s that I found, but it's possible I missed a few.

### CODE REVIEW

**Comment by chrisnharvey** [comment]
Hi there, thank you for your contribution.

That's quite a big change so we'll have to do some tests before merging, at first glance it all looks great though.

Thanks again.

**Comment by jchamberlain** [comment]
Also, this should fix issue #338. Welcome!

**Comment by jchamberlain** [comment]
Just looked at issue #336. If after testing you do decide to include these changes, it should only take a little bit more to fix that one too.

**Comment by jHoldroyd** [comment]
It looks fine, Chris is pulling it down now to test and we should get it merged for you soon

**Comment by jHoldroyd** [comment]
Thanks for this, we've got a few changes to make things a little easier but this is a great start and I think with this we found a fix to the settings issue too.

**Pull request merged**
