### PR TITLE
added lang function in shipping index view

### PR DESCRIPTION
**Pull request by ChristianGiupponi**
added lang function in shipping index view

### CODE REVIEW

**Comment by jHoldroyd** [comment]
Thanks again Christian, we're going to have to figure out a way to thank you for the awesome work taking care of the translations!

**Comment by ChristianGiupponi** [comment]
Glad to help!
As soon as I can I will send new pull request for the translation!
Now I have a problem with the fork so I don't know when...I don't know why but I can't update my fork with `git pull git://github.com/firesale/FireSALE.git` 
:S

**Comment by jHoldroyd** [comment]
Yeah we've been having a few issues since we stupidly decided to rename the repo, it's now FireSale

**Comment by ChristianGiupponi** [comment]
hell I had not noticed!
Thank you, tomorrow I'll try to update and see if it goes!

**Pull request merged**
